SocialMap/myTaiwanTest/Models/Sign.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myTaiwanTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sign()
        {
            this.Friends = new HashSet<Friend>();
            this.Texts = new HashSet<Text>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string passwords { get; set; }
        public string email { get; set; }
        public string faceUrl { get; set; }
        public string coverUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Text> Texts { get; set; }
    }
}

SocialMap/myTaiwanTest/Controllers/SignsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using myTaiwanTest.Models;

namespace myTaiwanTest.Controllers
{
    public class SignsController : Controller
    {
        private myTaiwanEntities db = new myTaiwanEntities();

        // GET: Signs
        public ActionResult Index()
        {
            return View(db.Signs.ToList());
        }

        // GET: Signs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sign sign = db.Signs.Find(id);
            if (sign == null)
            {
                return HttpNotFound();
            }
            return View(sign);
        }

        // GET: Signs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Signs/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,name,passwords,email,faceUrl,coverUrl")] Sign sign)
        {
            if (ModelState.IsValid)
            {
                db.Signs.Add(sign);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sign);
        }
        //註冊
        public ActionResult SignIn() {
            return View("Login");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignIn([Bind(Include = "name,passwords,email")] Sign sign) {
            if (ModelState.IsValid) {
                sign.coverUrl = "";
                sign.faceUrl = "";
                db.Signs.Add(sign);
                try
                {
                    db.SaveChanges();
                    var query = db.Signs.FirstOrDefault(o => o.name == sign.name &&
                                        o.passwords == sign.passwords);
                    if (query != null) {
                        Session["userName"] = query.name;
                        Session["userID"] = query.ID;
                        return RedirectToAction("BrowseText");
                    }
                    
                }
                catch(Exception ex)
                {
                    throw;
                }
            }
            return View("Login", sign);
        }


        public ActionResult LogIn()
        {
            int UserID = Convert.ToInt32(Session["userID"]);
            var sign = db.Signs.FirstOrDefault(o => o.ID == UserID);
            var BrowseText = db.sp_BrowseText(UserID);
            AddfriendPlusText mix = new AddfriendPlusText() {
                browseText = BrowseText,
                sign = sign
            };
            return View("DynamicIndex", mix);
        }
        //以使用者為主秀出文章
        public ActionResult BrowseText()
        {
            int UserID = Convert.ToInt32(Session["userID"]);
            var sign = db.Signs.FirstOrDefault(o => o.ID == UserID);
            var BrowseText = db.sp_BrowseText(UserID);
            AddfriendPlusText mix = new AddfriendPlusText() {
                browseText = BrowseText,
                sign = sign
            };
            return View("DynamicIndex", mix);
        }
        //以使用者為主秀出文章(限定地區)
        public ActionResult BrowseTextByCounty(string id) {
            int UserID = Convert.ToInt32(Session["userID"]);
            var sign = db.Signs.FirstOrDefault(o => o.ID == UserID);
            var countyID = db.Counties.First(c => c.countryName == id).countryID;
            var BrowseText = db.sp_BrowseTextbyCounty(UserID, countyID);
            AddfriendPlusText mix = new AddfriendPlusText() {
                browseTextbyCounty = BrowseText,
                sign = sign,
            };
            return View("DynamicIndex", mix);
        }

        //登入
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn([Bind(Include = "name,passwords")] Sign sign)
        {
            if (ModelState.IsValid)
            {
                //var query = from o in db.Signs
                //            where o.name == sign.name &&
                //                  o.passwords == sign.passwords
                //            select o;
                var query = db.Signs.FirstOrDefault(o => o.name == sign.name && 
                                        o.passwords == sign.passwords);
                try
                {
                    if (query != null)
                    {
                        Session["userName"] = query.name;
                        Session["userID"] = query.ID;
                        return RedirectToAction("BrowseText");
                    }
                        
                }
                catch(Exception ex)
                {
                    ;
                }
                
            }
            return View("Login");
        }
        //登出
        public ActionResult LogOut()
        {
            //Session.Clear();
            return View("Login");
        }
        //好友列表
        public ActionResult myFriend()
        {
            return View();
        }
        //尋找好友(路人) //由searchtext取得資料
        [HttpPost]
        public ActionResult searchUser([Bind(Include = "name")] Sign signFriend)
        {
            int UserID = Convert.ToInt32(Session["userID"]);
            var sign = db.Signs.FirstOrDefault(o => o.ID == UserID);
            AddfriendPlusText friendPage = new AddfriendPlusText();
            
            var friendTextDetail = db.Signs.FirstOrDefault(o => o.name == signFriend.name);//好友(路人)資訊
            friendPage.friendID = friendTextDetail.ID;
            friendPage.browseText = db.sp_BrowseText(friendTextDetail.ID);//文章資訊
            friendPage.FriendSign = friendTextDetail;
            friendPage.sign = sign;

            return View("FriendPage", friendPage);
        }
        //尋找好友 //由好友ID搜尋
        public ActionResult searchUser(int id) {
            int UserID = Convert.ToInt32(Session["userID"]);
            var sign = db.Signs.FirstOrDefault(o => o.ID == UserID);
            AddfriendPlusText friendPage = new AddfriendPlusText();

            var friendTextDetail = db.Signs.FirstOrDefault(o => o.ID == id);//好友資訊
            friendPage.friendID = friendTextDetail.ID;
            friendPage.browseText = db.sp_BrowseText(friendTextDetail.ID);//文章資訊
            friendPage.FriendSign = friendTextDetail;
            friendPage.sign = sign;
            return View("FriendPage", friendPage);
        }
        //文章列表
        //public ActionResult ArctileIndex()
        //{
        //    return View();
        //}
        //新增好友
        public ActionResult addFriend(int id)
        {
            int UserID = Convert.ToInt32(Session["userID"]);
            var sign = db.Signs.FirstOrDefault(o => o.ID == UserID);
            AddfriendPlusText friendPage = new AddfriendPlusText();

            Friend addFriend = new Friend() {
                userID = Convert.ToInt32(Session["userID"]),
                friendID = id
            };
            db.Friends.Add(addFriend);
            db.SaveChanges();
            var friendTextDetail = db.Signs.FirstOrDefault(o => o.ID == id);//好友(路人)資訊
            friendPage.friendID = friendTextDetail.ID;
            friendPage.browseText = db.sp_BrowseText(friendTextDetail.ID);//文章資訊
            friendPage.FriendSign = friendTextDetail;
            friendPage.sign = sign;

            return View("FriendPage", friendPage);
        }
        //刪除好友 
        public ActionResult delFriend(int id)
        {
            int UserID = Convert.ToInt32(Session["userID"]);
            var sign = db.Signs.FirstOrDefault(o => o.ID == UserID);
            AddfriendPlusText friendPage = new AddfriendPlusText();
            var delfriend = db.Friends.FirstOrDefault(o => o.userID == UserID && o.friendID == id);
            db.Friends.Remove(delfriend);
            db.SaveChanges();
            var friendTextDetail = db.Signs.FirstOrDefault(o => o.ID == id);//好友(路人)資訊
            friendPage.friendID = friendTextDetail.ID;
            friendPage.browseText = db.sp_BrowseText(friendTextDetail.ID);//文章資訊
            friendPage.FriendSign = friendTextDetail;
            friendPage.sign = sign;

            return View("FriendPage", friendPage);
        }

        //public ActionResult addText()
        //{
        //    return View();
        //}

        public ActionResult singleText() {
            return View("SingleText");
        }

        //仁廷好友列表
        public ActionResult myFriends()
        {
            int UserID = Convert.ToInt32(Session["userID"]);
            var userName = Session["userName"].ToString();
            var query = db.Friends.Where(o => o.userID == UserID);

            var friend = from o in db.Signs
                         from f in query
                         where o.ID == f.friendID
                         select o;
            List<Sign> list = friend.ToList();
            Sign updateFace = db.Signs.FirstOrDefault(o => o.name == userName);
            FriendPlusDelFriend mix = new FriendPlusDelFriend()
            {
                sign = updateFace,
                friendList = list
            };
            return View("myFriends", mix);

        }
        public ActionResult delFriend1(int id)
        {
            var userName = Session["userName"].ToString();
            Friend list1 = db.Friends.FirstOrDefault(o => o.friendID == id);
            db.Friends.Remove(list1);
            db.SaveChanges();
            int UserID = Convert.ToInt32(Session["userID"]);

            var query = db.Friends.Where(o => o.userID == UserID);

            var friend = from o in db.Signs

SocialMap/myTaiwanTest/Views/Signs/ArctileIndex.cshtml
@using myTaiwanTest.Models
@model FriendPlusDelFriend
@{
    Layout = "~/Views/layout/_ArctileLayout.cshtml";
}
<h3><i class="fa fa-angle-right"></i> 我的貼文</h3>
<div class="row">
    @{
        foreach (var articles in Model.locationInModel)
        {
            <div class="col-lg-4 col-md-4 col-sm-4 mb">
                <div class="content-panel pn">
                    <div id="blog-bg">
                        <div class="blog-title">@articles.city</div>
                        <div class="blog-btn" id="manger" onclick="mangerarticle()">
                            <p onclick="delText(@articles.txtID)">刪除貼文</p>
                        </div>
                    </div>
                    <div class="blog-text">
                        <div class="blog-dis">@articles.txtTitle</div>
                        <div class="blog-date">@articles.txtCreateTime</div>
                        <p>@Html.Raw(articles.txtText)</p>
                    </div>
                </div>
            </div><!-- /col-md-4-->

        }


    }
</div>  

<script>
    function delText(id) {
        window.location.href = "/signs/delText/"+id;
    }

</script>

SocialMap/myTaiwanTest/Views/Signs/Create.cshtml
@model myTaiwanTest.Models.Sign

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sign</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.passwords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.passwords, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.passwords, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.faceUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.faceUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.faceUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.coverUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.coverUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.coverUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SocialMap/myTaiwanTest/Views/Signs/Delete.cshtml
@model myTaiwanTest.Models.Sign

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sign</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.passwords)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.passwords)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.faceUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.faceUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.coverUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.coverUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SocialMap/myTaiwanTest/Views/Signs/Details.cshtml
@model myTaiwanTest.Models.Sign

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Sign</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.passwords)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.passwords)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.faceUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.faceUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.coverUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.coverUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SocialMap/myTaiwanTest/Views/Signs/DynamicIndex.cshtml
@using myTaiwanTest.Models
@model AddfriendPlusText
@{
    ViewBag.Title = "DynamicIndex";
    Layout = "~/Views/layout/_DynamicLayout.cshtml";
}

@* 挖洞 *@
<div class="dynamicTable">
    <ul class="dynamicBar">
        @if (Model != null) {
            if (Model.browseText != null) {
                foreach (var dr in Model.browseText) {
                    <li class="dynamicTextSpace">
                    <div class="dynamicBarView">
                        <div class="dynamicBarViewValue">
                            @if (dr.picUrl != "" && dr.picUrl != null) {
                                <img src="@dr.picUrl" class="dynamicBarViewValueImage" />
                            }
                            else {
                                <img src="~/image/SignInPic1.jpg" class="dynamicBarViewValueImage" />
                            }
                        </div>
                    </div>
                    <div class="dynamicBarText">
                        <div class="dynamicBarTextValue">
                            <label style="font-size:larger">@dr.name</label><br />
                            <label style="font-size:large;float:left">@dr.countryName</label>
                            <label style="font-size:large;float:right">@dr.txtUpdateTime</label><br />
                            <div style="word-break: break-all">@Html.Raw(dr.txtText)</div>
                        </div>
                    </div>
                    </li>
                }
            }
            else {
                foreach (var dr in Model.browseTextbyCounty) {
                    <li class="dynamicTextSpace">
                        <div class="dynamicBarView">
                            <div class="dynamicBarViewValue">
                                @if (dr.picUrl != "" && dr.picUrl != null) {
                                    <img src="@dr.picUrl" class="dynamicBarViewValueImage" />
                                }
                                else {
                                    <img src="~/image/SignInPic1.jpg" class="dynamicBarViewValueImage" />
                                }
                            </div>
                        </div>
                        <div class="dynamicBarText">
                            <div class="dynamicBarTextValue">
                                <label style="font-size:larger">@dr.name</label><br />
                                <label style="font-size:large;float:left">@dr.countryName</label>
                                <label style="font-size:large;float:right">@dr.txtUpdateTime</label><br />
                                <div style="word-break: break-all">@Html.Raw(dr.txtText)</div>
                            </div>
                        </div>
                    </li>
                }
            }
        }
        @*<li class="dynamicTextSpace">
                <div class="dynamicBarView">
                    <div class="dynamicBarViewValue">
                        <a>放圖片的div</a>
                    </div>
                </div>
                <div class="dynamicBarText">
                    <div class="dynamicBarTextValue">
                        <label style="font-size:larger">UserID</label><br />
                        <label style="font-size:large;float:left">地點</label>
                        <label style="font-size:large;float:right">時間</label><br />
                        <label style="word-break: break-all">234234567874567898765467898765645678654567578654567867897657678567</label>
                    </div>
                </div>
            </li>*@
    </ul>
</div>

SocialMap/myTaiwanTest/Views/Signs/Edit.cshtml
@model myTaiwanTest.Models.Sign

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sign</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.passwords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.passwords, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.passwords, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.faceUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.faceUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.faceUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.coverUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.coverUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.coverUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SocialMap/myTaiwanTest/Views/Signs/FriendPage.cshtml
@using myTaiwanTest.Models
@model AddfriendPlusText
@{
    ViewBag.Title = "FriendPage";
    Layout = "~/Views/layout/_FriendLayout.cshtml";
}

<div class="dynamicTable">
    <ul class="dynamicBar">
        @if (Model != null)
        {
            foreach (var dr in Model.browseText)
            {
                <li class="dynamicTextSpace">
                    <div class="dynamicBarView">
                        <div class="dynamicBarViewValue">
                            <img src="/image/SignInPic1.jpg" class="dynamicBarViewValueImage">
                        </div>
                    </div>
                    <div class="dynamicBarText">
                        <div class="dynamicBarTextValue">
                            <label style="font-size:larger">@dr.name</label><br />
                            <label style="font-size:large;float:left">@dr.countryName</label>
                            <label style="font-size:large;float:right">@dr.txtUpdateTime</label><br />
                            <div style="word-break: break-all">@Html.Raw(dr.txtText)</div>
                        </div>
                    </div>
                </li>
            }
        }
        else
        {
            <li class="dynamicTextSpace">

            </li>
        }

    </ul>
</div>

SocialMap/myTaiwanTest/Views/Signs/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html id="banner">
<head>
    <meta charset="UTF-8">
    <title>Day 001 Login Form</title>
    <!--<link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Open+Sans:600'>-->
    <link rel="stylesheet" href="~/css/style.css">
    <script src="/Scripts/jquery-1.11.2.min.js"></script>
    <script type="text/javascript">
        var banner = new Array()
        banner[0] = "/image/SignInPic1.jpg"
        //台南鹽田
        banner[1] = "/image/SignInPic2.jpg"
        //高雄市 月亮
        banner[2] = "/image/SignInPic3.jpg"
        //伯朗大道
        banner[3] = "/image/SignInPic4.jpg"
        //清水斷崖
        banner[4] = "/image/SignInPic5.jpg"
        //大101
        banner[5] = "/image/SignInPic6.jpg"
        //天使眼淚

        var random = Math.floor(banner.length * Math.random());
        document.write("<style>");
        document.write("#banner  {");
        document.write(' background:url("' + banner[random] + '") no-repeat center ;');
        document.write('background-size:cover;');
        document.write(" }");
        document.write("</style>");

    </script>
    <script type='text/javascript'>
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'7f9622f3-a9e0-4c05-a0c3-becb9fc9313b'
        });

        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>

</head>

<body>

    <div class="login-wrap">
        <div class="login-html">
            <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
            <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
            <div class="login-form">
                @using (Html.BeginForm("LogIn", "Signs"))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <div class="sign-in-htm">
                        <div class="group">
                            <label for="user" class="label" onclick="speedLogIn()">Username</label>
                            <input id="user" name="name" type="text" class="input">
                        </div>
                        <div class="group">
                            <label for="pass" class="label">Password</label>
                            <input id="pass" type="password" name="passwords" class="input" data-type="password">
                        </div>
                        <div class="group">
                            <input id="check" type="checkbox" class="check" checked>
                            <label for="check"><span class="icon"></span> Keep me Signed in</label>
                        </div>
                        <div class="group">
                            <input type="submit" class="button" value="Sign In">
                        </div>
                        <div class="hr"></div>
                        <div class="foot-lnk">
                            <a href="#forgot">Forgot Password?</a>
                        </div>
                    </div>
                }
                @using (Html.BeginForm("SignIn", "Signs"))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <div class="sign-up-htm">
                        <div class="group">
                            <label for="user" class="label" onclick="speedSignIn()">Username</label>
                            <input id="user1" name="name" type="text" class="input">
                        </div>
                        <div class="group">
                            <label for="pass" class="label">Password</label>
                            <input id="pass1" type="password" name="passwords" class="input" data-type="password">
                        </div>
                        <div class="group">
                            <label for="passcheck" class="label">Repeat Password</label>
                            <input id="passcheck" type="password" class="input" data-type="password">
                        </div>
                        <div class="group">
                            <label for="email" class="label">Email Address</label>
                            <input id="email1" name="email" type="text" class="input">
                        </div>
                        <div class="group">
                            <input type="submit" class="button" value="Sign Up">
                        </div>
                        <div class="hr"></div>
                        <div class="foot-lnk">
                            <label for="tab-1">Already Member?</label>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <script>
        function speedSignIn() {
            $("#user1").val("345");
            $("#pass1").val("345");
            $("#passcheck").val("345");
            $("#email1").val("345@345");
        }

        function speedLogIn() {
            $("#user").val("Milktea123");
            $("#pass").val("MilkteaPass");
        }
    </script>


</body>
</html>